### ISSUE TITLE
Add Nginx to serve static files

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/hamlet#211]
As discussed in #210.

**Comment by shaunanoordin** [comment]
Following the discussion on #210: D'oh! So it was totally different from what I was trying to solve.

> @adammcmaster 
> We'll need to add Nginx to the Kubernetes deployment. I'll open an issue for that – how soon do you need this to be working?

How soon can you get time to work on this? If <= a week, cool, I'll wait (I'll shift focus onto Survos instead) ; else if > week, I'll take a stab at learning to add the Nginx settings to the, uh, `kubernetes/deployment.tmpl` file (I think?)

The static files are the last piece needed to close the Microsoft dev work, but I understand you have other things on your plate so I won't press the priority on this right now.

**Comment by adammcmaster** [comment]
I'm off next week, so if it's urgent I can try to fit it in tomorrow/Friday, but if you don't mind giving it a go or waiting until I'm back then that would be easier.
