### ISSUE TITLE
"Outdated" auth sessions lead to 403 Errors

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/hamlet#235]
## Authentication Bug

Users have reported encountering 403 pages when trying to access a Project Page, e.g. `https://hamlet-staging.zooniverse.org/subject-assistant/1292/`

There are only 2 logical ways this can happen, as far as I can tell:

1. user switches user accounts in the middle of using the website, (e.g. by logging out and logging in on a separate tab,) and attempts to access a Project resource that their current user account doesn't have access to.
2. user stays on the home page for too long and their session times out. However, the UI doesn't doesn't realise the user isn't logged in, so it still shows the link to the Project Page, but the Project Page itself cannot be accessed (403) because it correctly detects that the user has an expired session.

Option 1 seems too convoluted to be encountered normally by a standard user, so I'm ruling that out. Option 2, however, I've experienced myself. I'm still trying get a consistent replication of the problem that _doesn't involve leaving a tab to Hamlet open overnight._

### Status

Major issue, but there is a workaround:

1. go to the hamlet home page - https://hamlet-staging.zooniverse.org/
2. log out, then log in again.

**Comment by camallen** [comment]
this should be fixed in #428 as i've modified the default session length to match the API bearer tokens
