### ISSUE TITLE
Replace "netcat" with "netcat-traditional"?

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/hamlet#447]
## Setup Issue

Currently, on ac473f261bc374a7d5b45da24021e474407f4252 at 5 Aug 2023, when I try to run `docker-compose build`, I error out with the message "Package 'netcat' has no installation candidate".

From what I can tell, [netcat](https://packages.debian.org/buster/netcat) is just a dummy/transitional package on Debian, and a quick fix is to use "netcat-traditional" (or netcat-openbsd) in the [Dockerfile](https://github.com/zooniverse/hamlet/blob/ac473f261bc374a7d5b45da24021e474407f4252/Dockerfile#L10).

### Status

I'm leaving a note here instead of applying the fix immediately, because as of 02:12 MYT, _I'm having a lot of OTHER trouble getting Hamlet running on localhost._ (Currently: can't find the Postgres server)

I'm not sure if this is just another "me" problem, or there are some recent updates to the dependency downline (or is that upline?) that borks the Hamlet build. (The last [successful build & deploy](https://github.com/zooniverse/hamlet/actions/workflows/deploy_production.yml) was done 6 months ago.)

In which case, I'm not committing any fixes until I can confirm wtf is going on. If somebody else fixes this before me, please add a note of what you discovered so I know what's up. Thanks!

**Comment by eatyourgreens** [comment]
Staging builds are broken too. 
https://github.com/zooniverse/hamlet/actions/runs/5782842967

**Comment by eatyourgreens** [comment]
The Docker build succeeds with `netcat-openbsd`. Let’s see if the app runs on staging without problems. 
https://github.com/zooniverse/hamlet/actions/runs/5783258974

**Comment by eatyourgreens** [comment]
Closed by #452.
