### ISSUE TITLE
Content Update required - Aug 2023

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/hamlet#448]
## Content Update

Sarah Huebner has prepared some copy/text that needs to be updated in Hamlet. This corresponds with the new text on Subject Assistant.

- Related PR on Subject Assistant: https://github.com/zooniverse/subject-assistant/pull/228
- The content to be updated: https://zooniverse.slack.com/archives/C0384N312G3/p1691000483134869 (Zooniverse Slack, `#subject-assistant` channel, from Sarah, date 3 Aug 02:21 MYT)

### Status

This should be done as soon as possible.

However, I'm currently having problems getting these simple updates out due to [local dev issues,](https://github.com/zooniverse/hamlet/issues/447) so this may take a while.

**Comment by eatyourgreens** [comment]
I've started a branch for this in #460.
